id: P403766FD
initial_creation_type: input
source_metadata:
  title: Tulku Urgyen Rinpoche
  language: en
  description: 'Texts by and about Tulku Urgyen Rinpoche (sprul sku o rgyan rin po
    che, 1920–1996), one of the most celebrated teachers of Dzogchen and Mahāmudrā
    in recent times:'
  volume:
    bd52c3b16c354e71b08d0f50ac5f2d42:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Calling the Guru from Afar
    018c1e5f95924a149afe4fec83ccfec3:
      title: In Praise of the Hidden Valley of Kyimolung
      parent: Pilgrimage
created_at: '2022-03-01T01:58:23.918738'
last_modified_at: '2022-03-01T01:58:23.918745'
